# Generated by Django 5.2.17 on 2026-09-09 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="smtpconfig",
            name="username",
            field=models.CharField(
                blank=True,
                help_text="Leave blank if your server doesn't require authentication.",
                max_length=255,
            ),
        ),
    ]
