# Generated by Django 5.2.17 on 2026-09-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0002_alter_smtpconfig_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sendingsession",
            name="body",
            field=models.TextField(
                help_text="HTML email body. Use {{name}} anywhere you want the recipient's name inserted."
            ),
        ),
    ]
